repos:
  - repo: local
    hooks:
      - id: shell-fmt-go
        name: shfmt
        description: Rewrites all shell scripts to a canonical format.
        language: golang
        additional_dependencies:
          - mvdan.cc/sh/v3/cmd/shfmt@v3.8.0
        entry: shfmt
        types:
          - file
          - shell
        exclude_types:
          - zsh
        args:
          - -w
          - -s
          - -l
          - -i
          - "2"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
