name: BATS Tests

on:
  pull_request:
  push:
    branches: [master, next]

  workflow_dispatch:

jobs:
  bats-alpine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bash: ["4.2", "4.4", "5.0", "5.2"]
    container:
      image: bash:${{ matrix.bash }}
    steps:
      - name: Install packages
        run: |
          # Pipeline requirements
          apk add curl git ncurses parallel sudo tar
          # Theme dependencies
          apk add bc coreutils gawk jq playerctl sed

      # Allow tar to cache system paths
      - name: root suid tar
        run: sudo chown root:wheel /bin/tar && sudo chmod u+s /bin/tar

      - name: Setup Bats and bats libs
        uses: stealthii/bats-action@main

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tokyo-night-tmux tests
        shell: bash -e {0}
        run: bats --verbose-run --report-formatter junit test/

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-alpine-${{ matrix.bash }}
          path: report.xml
  bats-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        libs: ["gnu", "builtin"]
    steps:
      - name: Install Homebrew packages
        run: |
          # Theme dependencies
          brew install bash jq nowplaying-cli
          if [[ "${{ matrix.libs }}" == "gnu" ]]; then
            brew install bc coreutils gawk gsed
          fi

      - name: Setup Bats and bats libs
        run: |
          brew install bats-core
          brew tap stealthii/bats-core
          brew install bats-support bats-assert bats-file bats-detik bats-mock

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tokyo-night-tmux tests
        run: bats --verbose-run --report-formatter junit test/

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-macOS-${{ matrix.libs }}
          path: report.xml
